server:
  port: 8080
  servlet.context-path: /
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: 123456@A
  jpa:
    show-sql: true
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        acknowledge-mode: manual
        default-requeue-rejected: false

mybatis:
  mapper-locations: classpath:com/turong/training/rabbitmq/mapper/*Mapper.xml
